In [24]:
%matplotlib inline

In [58]:
import pandas as pd
import numpy as np

In [59]:
df = pd.read_csv("Titanic Dataset.csv")

In [60]:
df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [61]:
# Display first 5 rows
print("🔹 First 5 Rows:")
print(df.head())

🔹 First 5 Rows:
   pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female
1       1         1                   Allison, Master. Hudson Trevor    male
2       1         0                     Allison, Miss. Helen Loraine  female
3       1         0             Allison, Mr. Hudson Joshua Creighton    male
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female

     age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.00      0      0   24160  211.3375       B5        S    2    NaN
1   0.92      1      2  113781  151.5500  C22 C26        S   11    NaN
2   2.00      1      2  113781  151.5500  C22 C26        S  NaN    NaN
3  30.00      1      2  113781  151.5500  C22 C26        S  NaN  135.0
4  25.00      1      2  113781  151.5500  C22 C26        S  NaN    NaN

                         home.dest
0                     St Louis, MO
1  Montreal, PQ / Chesterville, ON
2  Montreal, PQ / Chesterville, ON
3  Montreal, PQ / Chesterville, ON
4  Montreal, PQ / Chesterville, ON

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object
 10  embarked   1307 non-null   object
 11  boat       486 non-null    object
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB

In [63]:
df.isnull().sum()

pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [64]:
df.describe

<bound method NDFrame.describe of       pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton
1          1         1                   Allison, Master. Hudson Trevor
2          1         0                     Allison, Miss. Helen Loraine
3          1         0             Allison, Mr. Hudson Joshua Creighton
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
...      ...       ...                                              ...
1304       3         0                             Zabour, Miss. Hileni
1305       3         0                            Zabour, Miss. Thamine
1306       3         0                        Zakarian, Mr. Mapriededer
1307       3         0                              Zakarian, Mr. Ortin
1308       3         0                               Zimmerman, Mr. Leo

         sex    age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.00      0      0   24160  211.3375       B5        S    2
1       male   0.92      1      2  113781  151.5500  C22 C26        S   11
2     female   2.00      1      2  113781  151.5500  C22 C26        S  NaN
3       male  30.00      1      2  113781  151.5500  C22 C26        S  NaN
4     female  25.00      1      2  113781  151.5500  C22 C26        S  NaN
...      ...    ...    ...    ...     ...       ...      ...      ...  ...
1304  female  14.50      1      0    2665   14.4542      NaN        C  NaN
1305  female    NaN      1      0    2665   14.4542      NaN        C  NaN
1306    male  26.50      0      0    2656    7.2250      NaN        C  NaN
1307    male  27.00      0      0    2670    7.2250      NaN        C  NaN
1308    male  29.00      0      0  315082    7.8750      NaN        S  NaN

       body                        home.dest
0       NaN                     St Louis, MO
1       NaN  Montreal, PQ / Chesterville, ON
2       NaN  Montreal, PQ / Chesterville, ON
3     135.0  Montreal, PQ / Chesterville, ON
4       NaN  Montreal, PQ / Chesterville, ON
...     ...                              ...
1304  328.0                              NaN
1305    NaN                              NaN
1306  304.0                              NaN
1307    NaN                              NaN
1308    NaN                              NaN

[1309 rows x 14 columns]>

In [65]:
# Column names
print("\n🔹 Columns:")
print(df.columns)

🔹 Columns:
Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

In [66]:
df.columns = df.columns.str.strip()  # removes extra spaces

In [67]:
# Fill Embarked with mode (if exists in dataset)
if 'Embarked' in df.columns:
    df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

# Drop Cabin if present
if 'Cabin' in df.columns:
    df.drop(columns=['Cabin'], inplace=True)

In [68]:
# Encode Sex
if 'Sex' in df.columns:
    df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

# One-hot encode Embarked
if 'Embarked' in df.columns:
    df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

In [69]:
columns_to_drop = ['Name', 'Ticket', 'PassengerId']
df.drop(columns=[col for col in columns_to_drop if col in df.columns], inplace=True)

In [70]:

df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [71]:
df.isnull().sum()

pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [72]:
df['age'].fillna(df['age'].median(), inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19168\1654433547.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)

In [73]:
df.drop(columns=['cabin'], inplace=True)

In [74]:
df = pd.get_dummies(df, columns=['embarked'], drop_first=True)

In [75]:
df['body'].fillna(df['body'].median(), inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19168\2428105441.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['body'].fillna(df['body'].median(), inplace=True)

In [76]:
 df.drop(columns=['boat'], inplace=True)

In [77]:
df.drop(columns=['home.dest'], inplace=True)

In [78]:
df.isnull().sum()

pclass        0
survived      0
name          0
sex           0
age           0
sibsp         0
parch         0
ticket        0
fare          1
body          0
embarked_Q    0
embarked_S    0
dtype: int64

In [79]:
import matplotlib
matplotlib.use('TkAgg')  # or 'QtAgg'

import matplotlib.pyplot as plt
import seaborn as sns

In [80]:
if 'Survived' in df.columns:
    plt.figure()
    sns.countplot(x='Survived', data=df)
    plt.title("Survival Count")
    plt.show()

In [81]:
if 'Age' in df.columns:
    plt.figure()
    df['Age'].hist(bins=30)
    plt.title("Age Distribution")
    plt.xlabel("Age")
    plt.ylabel("Frequency")
    plt.show()

In [82]:
numeric_df = df.select_dtypes(include=['number'])

plt.figure(figsize=(10, 6))
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

In [83]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [84]:
target_col = 'survived'

# Ensure target exists
if target_col not in df.columns:
    raise Exception("Target column 'survived' not found!")

# Features (drop target)
X = df.drop(columns=[target_col])
y = df[target_col]

In [85]:
# -------------------------
# PREPARE DATA (FIXED)
# -------------------------

X = df.drop(columns=['survived'])

# Keep only numeric
X = X.select_dtypes(include=['number'])

# Fill missing values
X = X.fillna(X.median())

y = df['survived']

In [86]:
# -------------------------
# CLEAN DATA FOR MODEL
# -------------------------

# Drop target separately
y = df['survived']

# Drop non-useful + string columns
X = df.drop(columns=[
    'survived',
    'name',
    'ticket',
    'home.dest',
    'cabin',
    'boat',
    'body'
], errors='ignore')

# Convert categorical to numeric (if any left)
X = pd.get_dummies(X, drop_first=True)

# Fill missing values
X = X.fillna(X.median())

print("\n🔹 Final Features Used:")
print(X.columns)

🔹 Final Features Used:
Index(['pclass', 'age', 'sibsp', 'parch', 'fare', 'embarked_Q', 'embarked_S',
       'sex_male'],
      dtype='object')

In [87]:



X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [88]:
print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

Training Data Shape: (1047, 8)
Testing Data Shape: (262, 8)

In [89]:

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

print("\n✅ Model Training Completed!")

✅ Model Training Completed!

In [90]:
y_pred = model.predict(X_test)

In [91]:
accuracy = accuracy_score(y_test, y_pred)
print(f"\n🎯 Accuracy: {accuracy:.4f}")

print("\n🔹 Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\n🔹 Classification Report:")
print(classification_report(y_test, y_pred))

🎯 Accuracy: 0.7748

🔹 Confusion Matrix:
[[127  17]
 [ 42  76]]

🔹 Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.88      0.81       144
           1       0.82      0.64      0.72       118

    accuracy                           0.77       262
   macro avg       0.78      0.76      0.77       262
weighted avg       0.78      0.77      0.77       262